#!/usr/bin/python3
# SPDX-FileCopyrightText; 2023 Ryosuke Suxuki ryo135791113@gmail.com
import sys

def tonum(s):   #def 関数の名前(引数)で関数を定義
  try:
      return int(s)
  except:
      return float(s)

ans = 0
for line in sys.stdin:
      ans += tonum(line)
print(ans)             
